export const set_city = 'set_city'
export const set_district = 'set_district'
export const set_ward = 'set_ward'
export const set_cities = 'set_cities'
export const set_districts = 'set_districts'
export const set_wards = 'set_wards'
export const reset = 'reset'
